/**
 * generateVerifyPayload.js
 * ------------------------
 * Extracts the EXACT compile input (all sources + compiler settings) from
 * Hardhat's build-info, so you can verify the deployed contract on
 * Polygonscan using the "Solidity (Standard JSON-Input)" method.
 *
 * Why: Polygonscan's "Single file" verifier cannot resolve
 *      @openzeppelin/contracts/... imports. The Standard JSON-Input method
 *      embeds every source file, so no import resolution is needed — and the
 *      bytecode matches exactly (same settings: solc 0.8.28, viaIR, runs 200).
 *
 * Usage:
 *   cd OptiCut-Backend
 *   npx hardhat compile        # (if you haven't compiled the deployed code yet)
 *   node scripts/generateVerifyPayload.js
 *
 * Then open https://amoy.polygonscan.com/address/<YOUR_CONTRACT> → Contract →
 * Verify and Publish → fill the form (see instructions below) and paste the
 * contents of verify-input.json into the "Enter the Solidity Contract Code"
 * box.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const buildInfoDir = path.join(__dirname, "..", "artifacts", "build-info");

if (!fs.existsSync(buildInfoDir)) {
  console.error("❌ No artifacts/build-info found. Run `npx hardhat compile` first.");
  process.exit(1);
}

const files = fs
  .readdirSync(buildInfoDir)
  .filter((f) => f.endsWith(".json") && !f.endsWith(".output.json"))
  .sort();

if (files.length === 0) {
  console.error("❌ No build-info json found. Run `npx hardhat compile` first.");
  process.exit(1);
}

const bi = JSON.parse(fs.readFileSync(path.join(buildInfoDir, files[0]), "utf8"));
const input = bi.input;

const outPath = path.join(__dirname, "..", "verify-input.json");
fs.writeFileSync(outPath, JSON.stringify(input, null, 2));

const sizeMB = (fs.statSync(outPath).size / (1024 * 1024)).toFixed(2);
const numSources = Object.keys(input.sources).length;

console.log("✅ Wrote verify-input.json  (" + sizeMB + " MB, " + numSources + " source files)");
console.log("");
console.log("── FORM SETTINGS FOR POLYGONSCAN ──");
console.log("  Compiler Type:       Solidity (Standard JSON-Input)");
console.log("  Compiler Version:    " + (bi.solcLongVersion || bi.solcVersion));
console.log("  EVM Version:         " + (input.settings?.evmVersion || "(default)"));
console.log("  Optimization:        " + (input.settings?.optimizer?.enabled ? "Yes, runs " + input.settings.optimizer.runs : "No"));
console.log("  viaIR:               " + (input.settings?.viaIR ? "Yes (enabled)" : "No"));
console.log("  Open Source License: MIT License (other license type)");
console.log("  Constructor Args:    (leave empty — OptiCut takes none)");
console.log("");
console.log("Then paste the FULL contents of verify-input.json into the code box and click");
console.log("'Verify and Publish'. A green 'Successfully generated bytecode' message means done.");
